---
- name: Set up infrastructure-related parameters
  template:
    src: '{{ playbook_dir }}/templates/parameters.yml.dist'
    dest: '{{ ansistrano_release_path.stdout }}/app/config/parameters.yml'

- name: Install Composer dependencies
  composer:
    command: install
    working_dir: '{{ ansistrano_release_path.stdout }}'

- name: Clear the cache
  command: '{{ release_console_path }} cache:clear --no-warmup --env=prod'

- name: Warm up the cache
  command: '{{ release_console_path }} cache:warmup --env=prod'

- name: Setup directory permissions for var/
  file:
    path: "{{ release_var_path }}"
    state: directory
    mode: 0777
    recurse: true
