---
- name: Install Nginx web server
  become: true
  apt:
    name: nginx
    state: latest
  notify: Restart Nginx

- name: Add Symfony config template to the Nginx available sites
  become: true
  template:
    src: templates/symfony.conf
    dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
  notify: Restart Nginx

- name: Enable Symfony config template from Nginx available sites
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    state: link
  notify: Restart Nginx

- name: Add enabled Nginx site to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ server_name }}"
    line: "127.0.0.1 {{ server_name }}"
