---
- hosts: webserver

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml

  vars_prompt:
    - name: git_branch
      prompt: 'Enter a branch of Git repository (can be the full SHA-1 hash, a branch name, or a tag name)'
      default: master
      private: no

  vars:
    release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
    release_var_path: "{{ ansistrano_release_path.stdout }}/var"
    release_logs_path: "{{ release_var_path }}/logs"
    release_sessions_path: "{{ release_var_path }}/sessions"

    # Ansistrano vars
    ansistrano_deploy_to: "{{ project_deploy_dir }}" # Base path to deploy to.
    ansistrano_deploy_via: git # Method used to deliver the code to the server. Options are copy, rsync, git, svn, s3 or download

    # Variables used in the Git deployment strategy
    ansistrano_git_repo: "git@github.com:knpuniversity/ansible.git" # Location of the git repository
    ansistrano_git_branch: "{{ git_branch }}" # What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa" # If specified this file is copied over and used as the identity key for the git commands, path is relative to the playbook in which it is used

    # Hooks: custom tasks if you need them
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

  environment:
    SYMFONY_ENV: prod

  roles:
    - carlosbuenosvinos.ansistrano-deploy
