---
- hosts: vb

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe

    - name: Install cowsay - it's probably important
      become: true
      apt:
        name: cowsay

    - name: Install Git VCS
      become: true
      apt:
        name: git
        state: latest

    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest

    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP CLI
      become: true
      apt:
        name: php7.1-cli
        state: latest
